# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import logic_clock_pb2 as logic__clock__pb2


class LogicalTimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.update_time_logical = channel.unary_unary(
                '/LogicalTime/update_time_logical',
                request_serializer=logic__clock__pb2.Request.SerializeToString,
                response_deserializer=logic__clock__pb2.Response.FromString,
                )


class LogicalTimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def update_time_logical(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogicalTimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'update_time_logical': grpc.unary_unary_rpc_method_handler(
                    servicer.update_time_logical,
                    request_deserializer=logic__clock__pb2.Request.FromString,
                    response_serializer=logic__clock__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LogicalTime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogicalTime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def update_time_logical(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LogicalTime/update_time_logical',
            logic__clock__pb2.Request.SerializeToString,
            logic__clock__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
